# Generated by Django 2.2.4 on 2021-04-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('password_2', models.CharField(max_length=8)),
            ],
        ),
    ]
