# Generated by Django 2.2.4 on 2021-05-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turbo_app', '0003_deliv_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliv_form',
            name='about_product',
        ),
        migrations.RemoveField(
            model_name='deliv_form',
            name='auction_time',
        ),
        migrations.RemoveField(
            model_name='deliv_form',
            name='deliv_method',
        ),
        migrations.RemoveField(
            model_name='deliv_form',
            name='p_waight',
        ),
        migrations.RemoveField(
            model_name='deliv_form',
            name='pickup_time',
        ),
    ]
