# Generated by Django 2.2.4 on 2021-05-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turbo_app', '0004_auto_20210502_2033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='deliv_form',
        ),
    ]
