# Generated by Django 2.2.4 on 2021-05-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bid_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='deliv_form',
            name='deliv_form_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
