# Generated by Django 2.2.4 on 2021-05-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0002_auto_20210508_1912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bid_table',
        ),
    ]
