# Generated by Django 2.2.4 on 2021-05-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0003_delete_bid_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='bid_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.IntegerField()),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
    ]
