# Generated by Django 2.2.4 on 2021-05-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0004_bid_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bid_table',
        ),
    ]
