# Generated by Django 2.2.4 on 2021-05-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0006_bid_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid_table',
            name='username',
            field=models.CharField(default='venkat', max_length=30),
            preserve_default=False,
        ),
    ]
