# Generated by Django 2.2.4 on 2021-05-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0008_auto_20210509_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid_table',
            name='deliv_form_id',
            field=models.IntegerField(null=True),
        ),
    ]
