# Generated by Django 2.2.4 on 2021-05-13 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0012_auto_20210513_1036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bid_table',
        ),
        migrations.DeleteModel(
            name='deliv_form',
        ),
    ]
