# Generated by Django 2.2.4 on 2021-05-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sample_app', '0013_auto_20210513_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='bid_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('deliv_form_id', models.IntegerField(null=True)),
                ('bid_amount', models.IntegerField()),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='deliv_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliv_form_id', models.IntegerField()),
                ('username', models.CharField(max_length=30)),
                ('sender_name', models.CharField(max_length=30)),
                ('sender_email_id', models.EmailField(max_length=254)),
                ('sender_phone_no', models.IntegerField()),
                ('sen_d_no', models.IntegerField()),
                ('sen_city', models.CharField(max_length=30)),
                ('sen_state', models.CharField(max_length=30)),
                ('sen_district', models.CharField(max_length=30)),
                ('sen_pincode', models.IntegerField()),
                ('sen_land_mark', models.CharField(max_length=30)),
                ('rec_name', models.CharField(max_length=30)),
                ('rec_email_id', models.EmailField(max_length=254)),
                ('rec_phone_no', models.IntegerField()),
                ('rec_d_no', models.IntegerField()),
                ('rec_city', models.CharField(max_length=30)),
                ('rec_state', models.CharField(max_length=30)),
                ('rec_district', models.CharField(max_length=30)),
                ('rec_pincode', models.IntegerField()),
                ('rec_land_mark', models.CharField(max_length=30)),
                ('about_product', models.CharField(max_length=130)),
                ('pro_waight', models.CharField(max_length=30)),
                ('pickup_time', models.CharField(max_length=30)),
                ('auction_time', models.DateTimeField(blank=True, null=True)),
                ('auct_time', models.CharField(max_length=10)),
                ('auct_year', models.IntegerField()),
                ('auct_day', models.CharField(max_length=10)),
                ('auct_month', models.CharField(max_length=10)),
                ('auction_status', models.CharField(default='live', max_length=30)),
                ('time_stamp', models.DateTimeField()),
                ('min_bid_amnt', models.IntegerField(default='None')),
            ],
        ),
    ]
