# Generated by Django 2.2.4 on 2021-05-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0015_auto_20210513_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliv_form',
            name='achived_by',
            field=models.CharField(default='prasanna', max_length=30),
            preserve_default=False,
        ),
    ]
